class Config:
    EARLIEST_ENABLE_HOUR = 6
    EARLIEST_ENABLE_MINUTE = 0
    LATEST_DISABLE_HOUR = 22
    LATEST_DISABLE_MINUTE = 0
    RASPBERRY_PI_DATA_PIN = 16 #GPIO23
    TRANSMITTER_CODE = 44756010
